[project]
name = "lm_builder"
version = "0.0.1"
description = "Python framework for building language models"
readme = "README.md"
requires-python = ">=3.11,<3.12"
authors = [
    { name = "Lazaro Hurtado" }
]
license = { text = "MIT" }
dependencies = [
    "pyyaml",
    "torch",
]

[project.optional-dependencies]
examples = [
    "datasets>=3.1.0",
    "python-dotenv",
    "tqdm>=4.67.1",
    "transformers",
]

[dependency-groups]
dev = [
    "black",
    "pylint",
    "pytest",
    "lm_builder[examples]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["lm_builder"]

[tool.pylint.main]
py-version = "3.11"
fail-under = 9.5

[tool.pylint.format]
max-line-length = 100

[tool.pylint."messages control"]
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "use-implicit-booleaness-not-comparison-to-string",
    "use-implicit-booleaness-not-comparison-to-zero",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "wrong-import-order",
    "use-dict-literal",
    "too-few-public-methods",
    "too-many-instance-attributes",
]
